### ISSUE TITLE
Error when trying to add profile picture

### ISSUE THREAD

**Issue by simplybenuk** [nhsengland/futurenhs#141]
When editing your profile and trying to upload a profile picture it returns the following message when trying to save

"There is a problem

An unexpected error occurred when attempting to update the user"

**Comment by MathewBeldon** [comment]
This should be fixed as part of story 89853(#128) same with #138

**Comment by Alex-Grubba-CDS** [comment]
@simplybenuk Please can you confirm if resolved? If so we can close this and #138

**Comment by simplybenuk** [comment]
@Alex-Grubba-CDS still getting the same results on live when I try and upload a pic and add pronouns

**Comment by Matt-Beldon-CDS** [comment]
Don't think it's been pushed to prod yet, still only on devtest

**Comment by simplybenuk** [comment]
Once these are all working on prod, I can close any that are fixed

**Comment by simplybenuk** [comment]
This is fixed now
